### ISSUE TITLE
Error running streamlit

### ISSUE THREAD

**Issue by philiprhoades** [abdouaziz/blenderbot#1]
abdouaziz,

This exercise was painless but I get this below - not familiar enough with Python to know what is wrong (on a newly installed Fedora 37 box):

```
$ streamlit run src/main.py
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "/home/phr/.local/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/delta_generator.py", line 38, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 28, in <module>
    from streamlit.runtime.app_session import AppSession
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/app_session.py", line 36, in <module>
    from streamlit.runtime import caching, legacy_caching
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/caching/__init__.py", line 21, in <module>
    from streamlit.runtime.state.session_state import WidgetMetadata
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/state/__init__.py", line 16, in <module>
    from streamlit.runtime.state.safe_session_state import (
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 20, in <module>
    from streamlit.runtime.state.session_state import (
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 44, in <module>
    from streamlit.type_util import ValueFieldName, is_array_value_field_name
  File "/home/phr/.local/lib/python3.11/site-packages/streamlit/type_util.py", line 35, in <module>
    import pyarrow as pa
  File "/home/phr/.local/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/lib.pyx", line 37, in init pyarrow.lib
ImportError: numpy.core.multiarray failed to import
```

**Comment by abdouaziz** [comment]
> abdouaziz,
> 
> This exercise was painless but I get this below - not familiar enough with Python to know what is wrong (on a newly installed Fedora 37 box):
> 
> ```
> $ streamlit run src/main.py
> RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
> Traceback (most recent call last):
>   File "/home/phr/.local/bin/streamlit", line 5, in <module>
>     from streamlit.web.cli import main
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/__init__.py", line 55, in <module>
>     from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/delta_generator.py", line 38, in <module>
>     from streamlit import config, cursor, env_util, logger, runtime, type_util, util
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/cursor.py", line 18, in <module>
>     from streamlit.runtime.scriptrunner import get_script_run_ctx
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
>     from streamlit.runtime.runtime import Runtime as Runtime
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 28, in <module>
>     from streamlit.runtime.app_session import AppSession
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/app_session.py", line 36, in <module>
>     from streamlit.runtime import caching, legacy_caching
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/caching/__init__.py", line 21, in <module>
>     from streamlit.runtime.state.session_state import WidgetMetadata
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/state/__init__.py", line 16, in <module>
>     from streamlit.runtime.state.safe_session_state import (
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 20, in <module>
>     from streamlit.runtime.state.session_state import (
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 44, in <module>
>     from streamlit.type_util import ValueFieldName, is_array_value_field_name
>   File "/home/phr/.local/lib/python3.11/site-packages/streamlit/type_util.py", line 35, in <module>
>     import pyarrow as pa
>   File "/home/phr/.local/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
>     import pyarrow.lib as _lib
>   File "pyarrow/lib.pyx", line 37, in init pyarrow.lib
> ImportError: numpy.core.multiarray failed to import
> ```

Hi @philiprhoades, thanks for reporting this issue , to correct this  : 
> Update the version of numpy with this command : `pip install numpy --upgrade `
> run the streamlit app 
Let me know if they are any others issues

**Comment by philiprhoades** [comment]
Yes! - that fixed the problem . . I am testing this on my newly installed Fedora 37 workstation but maybe I should be this exercise in a Podman container, not worry about RPM package management and do everything after installing Python with pip?
