### ISSUE TITLE
PEFT for BB

### ISSUE THREAD

**Issue by Lkh97** [abdouaziz/blenderbot#2]
Hi there,

I need to finetune BlenderBot with Lora PEFT config. However, I can not find the target module keyword that is needed to be set. Can you help with that, please?

**Comment by abdouaziz** [comment]
Hello @Lkh97, sorry for the delay. I have looked into the issue you reported about Blenderbot. I'm not sure if it has been resolved yet. Could you please explain what you mean by "Target module keyword"?
